### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by zhaowei699** [qd-cae/qd-cae-python#11]
1. node object can get coords by argument 'iTimestep=x', but get_disp() and get_acce() can not use the same method.
2. binout class only return some array, we can not use node object to do with binout.read('nodout').
3. keyfile class can not auto-ignore encrypted file(*.asc files)

**Comment by qd-codie** [comment]
thanks for the recommendations, they will help me improve the library. 
1 and 3 should be quite simple. 
2 though is more problematic,, since the binout class is not yet in C++, and thus I can not use my mesh datastructure.

**Comment by qd-codie** [comment]
I though about all three and came to the following conclusions, questions and suggestions.

1. While I agree, that all methods should have the same style, I would rather prefer your recommendation the other way around and remove the argument from `node.get_coords()`.
Explanation: This makes sense, because I would have to give `iTimestep` a default value (e.g. 0), but this would output the vector only at timestep zero and not the entire time series of the vector. A default value of `None` might seem reasonable to do so, but in C++ I can not assign a `nullptr` to an integer. It should fine though to simply use: `node.get_disp()[4]` instead of `node.get_disp(iTimestep=4)`, though it will have a minor performance penalty.
2. Seems fine to me, but will be a lot of work
3. How does dyna recognize, that the file is encrypted? I could not find any hint in the manual. Do you have knowledge about that?

**Comment by zhaowei699** [comment]
Some comments for three items:
1. It is good, I have used node.get_disp()[step] method to instead of iTimestep=x.
2. It can't effect my work and I also can deal with these arrarys. Only suggest what can be improved.
3. I think you can judge the line "-----BEGIN PGP MESSAGE-----" as begin and the line "-----END PGP MESSAGE-----" as end. Maybe you can consult dyna support (Oliver Graf <oliver.graf@dynamore.de>) to get prefessional answer.

**Comment by qd-codie** [comment]
(1) was fixed in 0.6.3.

**Comment by zhaowei699** [comment]
Thanks, I think you also update your document https://qd-cae.github.io/qd-cae-python/build/html/qd_cae_dyna_Node.html. Perfect work.

**Comment by qd-codie** [comment]
(3) will be fixed in 0.6.4
`KeyFile` will have a new signature 
```python
KeyFile(filepath, load_includes=True, encryption_detection=0.7)
```
The last argument is used in order to filter out encrypted include files. An encrypted (or compressed) file usually has a very high file entropy. The threshold controls the filter, where 0 means the file is perfectly structured and 1 means, that the file is entirely random. For testing, the file entropy can be derived by:

```python
from qd.cae.dyna import get_file_entropy

# the entropy of a file varies between [0,8]
entropy = get_file_entropy("path/to/encrypted_include")
entropy
>>> 7.64367
get_file_entropy("path/to/normal_include")
>>> 3.12390

encryption_detection = entropy/8
```



I will close the issue here, since (2) is too far into the future currently.

**Comment by zhaowei699** [comment]
Thanks a lot, I will update my qd to new version.

**Comment by qd-codie** [comment]
Might take a few days more, the tests did fail on linux.
