### ISSUE TITLE
*END keyword implementation request

### ISSUE THREAD

**Issue by hoo-ray** [qd-cae/qd-cae-python#21]
Stop parsing keywords after occurrence of *END keyword, possibly treat remainder of file as comment.

**Comment by qd-codie** [comment]
Hmm people often use *END to exclude old fragments etc. Since I wanted the rewritten file to be the same, I simply did not care about it. It is possible though to add data behind *END to the keyword itself. I'm just not sure about the benefit of this.

**Comment by qd-codie** [comment]
@hoo-ray what do you think would be the benefit of this? Though about it and the only topic which makes sense would be to exclude mesh keywords behind *END from getting parsed ... This indeed would be a bug in my eyes

**Comment by hoo-ray** [comment]
I see that you do not want to simply ignore/delete/comment out everything after an *END keyword for the sake of being able to save the keyfile with the original unmodified content.
The cleanest solution would be to add a new keyword property "Enabled": every keyword before (including) the *END is Eneabled=true, the remainder is Enabled=false. Disabled keywords will not get parsed into the DB, no matter what type of keyword they are (mesh, material, load, database, ...). They should not even be accessible to the user for deletion or modification because they are not active in the input deck. Maybe the new Enabled property should be private, not public, so the user cannot mess with it (maybe "Active" is a better name for the property).
If the only enabled *END keyword gets deleted in the keyfile object, then all succeeding keywords must be automatically enabled - until another (disabled) *END keyword or EOF is found.

**Comment by qd-codie** [comment]
Hmmm yeah this could be a solution. To be honest I don't care if we would append data behind *END as comments, since it would also be positioned correctly after *END again. My suggestion is just if you take away the access to all the keywords behind *END you kind a disallow people to maybe shuffle a keyword from behind *END into the front. 
Nonetheless mesh keywords etc behind *END should definitely not run `kw.load` . If you don't run this function the database simply just holds the data as string which is the same as if we would append it to *END. 
As a trade-off between our opinions I can image a flag in the constructor which discards stuff behind *END.

**Comment by qd-codie** [comment]
I now prevented the bug from loading keywords behind *END, do you still want a flag to discard all keywords behind *END?

**Comment by qd-codie** [comment]
Thanks, will implement it and and then close the issue. Looks like a bugfix for 0.8.1
