### ISSUE TITLE
judge elements intersection among different parts

### ISSUE THREAD

**Issue by zhaowei699** [qd-cae/qd-cae-python#26]
Hi, 
Sometimes, we use script to create model but we want to check whether the elements of parts have intersection before defining contact. Do you want to develop the new function to check elements intersection?
I have thought about it for many days and I can't think out a good arithmetic to do it. so I think maybe other people have the same request as me.

**Comment by qd-codie** [comment]
Hi Wei,
thanks for the suggestion. Collision detection is not difficult but annoying :stuck_out_tongue: Since we are already preparing release 0.8.0, it will not be around soon. I have been asked for nearest neighbor search stuff before, so I guess it will make sense to incorporate it sooner or later. 

Question: would this search also involve a contact thickness?

A good workaround for the moment is to take two close parts, search for every `Element` of `Part` 1 the nearest neighbor `Element` of `Part` 2 with a `sklearn.neighbors.KDTree`, which is highly efficient, and then check an element to element penetration. You will need a `KDTree` for every Part.The `KDTree` can query either the nearest neighbors and/or within a radius. The algorithm won't be ridiculously fast but should be sufficient if you only compare close parts.

**Comment by zhaowei699** [comment]
Hi Codie
Thanks a lot
Congratulate your team for the new version 0.8.0 will be released, it is very useful for us.
For me, I only want to check elements intersection and needn’t to check contact thickness or shell penetration.
Thanks for your suggestion but I never heard of “sklearn.neighbors.KDTree”, so I can’t understand it. I only know how to use “qd.cae.dyna” in python script, do you have some documents for introducing “KDTree”?

**Comment by zhaowei699** [comment]
Thanks, I found it in here:
http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KDTree.html
