### ISSUE TITLE
'RuntimeError: Could not re-enable console output.' when running "D3plot('d3plot')"

### ISSUE THREAD

**Issue by TomforGitHub** [qd-cae/qd-cae-python#30]
Hi Codie, 

I installed the qd module successfully with command `pip install qd`.  

The system info is  `3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]`

When I tried to load a d3plot file with `D3plot('d3plot')`, an error showed: `RuntimeError: Could not re-enable console output.`

**Comment by qd-codie** [comment]
Hey,
are you using FEMZIP decompression or is it a plain D3plot file?

**Comment by qd-codie** [comment]
**Detailed Explanation**
I've investigated the issue. The problem originates as follows. 
In the newest version I automatically detect whether the file was compressed by femzip or not. Unfortunately femzip writes to the console during the test and I had to use a hack to disable this without having access to their source code. Therefore I simply disable `stdout` while testing for compression. After the test I re-enable stdout again and this exactly fails in your case. I tested the solution on windows and linux and in my case it did work, but the code was also compiled on the very same machines ... 

**Solutions**
I can compile a version without femzip and upload it into the dist folder for you tomorrow. Otherwise an older version should also work.

**Comment**
The most recent features made unfortunately the code less reliably in terms of portability on windows, but windows is known to give one a hard time to make code portable ... I decided to focus the next minor versions to raise stability. Unfortunately I can not reproduce certain issues on my machines which makes life quite tough. I'm not giving up though.

**Comment by TomforGitHub** [comment]
I successfully installed `qd-0.7.3-cp36-cp36m-win_amd64.whl`, and `D3plot` can be imported. But when I run `D3plot('d3plot')`, this error occurs: 
`RuntimeError: Wrong filetype 538976288 != 1 (or 5) in header of d3plot. Your file might be in Double Precision or the endian of the file is not the endian of the machine.`

**Comment by qd-codie** [comment]
Is it a double precision file?

**Comment by qd-codie** [comment]
This is a compiled version of 0.8.0 without FEMZIP if you still require it.

[qd-0.8.0-cp36-cp36m-win_amd64.whl.zip](https://github.com/qd-cae/qd-cae-python/files/2224426/qd-0.8.0-cp36-cp36m-win_amd64.whl.zip)

**Comment by TomforGitHub** [comment]
I installed verison 0.8.0, and I'll output single precision results and see. Thanks for your time!

**Comment by qd-codie** [comment]
Glad I could (partially) help. I will close this issue and open a new one with a request for double precision handling.
