### ISSUE TITLE
Could not import submodule dyna_cpp with error message

### ISSUE THREAD

**Issue by nikorose87** [qd-cae/qd-cae-python#37]
Hi 

Trying to install on CentOS 7 I am having problems with the compilation, I installed `gcc` and `g++` 8.1.0, and the installation run well, however, the test did not, the test shows the following error:

> ImportError: Could not import submodule dyna_cpp with error message: /home..../qd-cae-python/qd/cae/dyna_cpp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt6thread6_StateE

The problem is that I cannot use anaconda because they work with a `4.8.5 gcc` version, and if a use the new version of `gcc` they suggest me to use the anaconda version.

Any suggestion?
Thanks.

**Comment by qd-codie** [comment]
Don't worry, I got it running with gcc7 so you should also get it work.

I assume you are using the OS python version. The bug clearly refers to threading. Maybe because the wrong OpenMP library was used by python. You will not get a large penalty by simply disabling OpenMP. You can do that by openining the `setup.py` and set `use_openmp = False` and rerun.

What I usually do:
Iam indeed usually using Anaconda even on Linux. My major issues on Linux where usually wrong  `*.so` used by the library. In general it always worked reliably by simply creating a new environment (e.g. python 3.6) and installing it within this Anaconda environment. It seems to prevent many of these issues. 

Let me know if it worked.

**Comment by nikorose87** [comment]
Thank you so much for the suggestion and, specially, for the quick answer.

The test run perfect creating a new environment. I had only one trouble, I did not that version with checkout, I had to install version `0.8.0`. 

Bye

**Comment by qd-codie** [comment]
Glad it worked. I just warn you here that I received a model where the stress values were wrong in 0.8, so if you want to be save here is the link:

https://github.com/qd-cae/qd-cae-python/tree/0.7.4
