### ISSUE TITLE
Problems intalling on server

### ISSUE THREAD

**Issue by nikorose87** [qd-cae/qd-cae-python#52]
Hi Codie,

I am having troubles installing your library on the server. I could load the gcc 4.9.4 and 5.3.0. Either of them installed without problems, however on the test process the following messages are shown:

`
Traceback (most recent call last):
  File "/N/u/eprietop/Karst/anaconda3/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/N/u/eprietop/Karst/anaconda3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/gpfs/home/e/p/eprietop/Karst/qd-cae-python/test/test_dyna.py", line 12, in <module>
    from qd.cae.dyna import *
  File "/gpfs/home/e/p/eprietop/Karst/qd-cae-python/qd/cae/dyna.py", line 7, in <module>
    "Could not import C++ Submodule dyna_cpp with error message: %s." % str(err))
ImportError: Could not import C++ Submodule dyna_cpp with error message: /gpfs/home/e/p/eprietop/Karst/qd-cae-python/qd/cae/dyna_cpp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz.
`
I do not know how can I make this to work.

Thanks in advance!

**Comment by lasso-codie** [comment]
It's an issue with your server environment. The library gets compiled against a system library but at runtime tries to use one with a different version causing the failure. This may happen on linux with anaconda which has different runtime libraries than the system ones. That's why I usually use a specific conda environment to avoid this. Without digging deeper into the system myself I can't tell more though.

**Comment by lasso-codie** [comment]
Do you have any insights to share? Otherwise I would just close the issue since it is not related directly to the code.

**Comment by nikorose87** [comment]
Sorry for the delay! I haven't had the time to explore on this issue, however, you can close it! I will let you know If I can solve it.
