### ISSUE TITLE
Wrong shell element value 

### ISSUE THREAD

**Issue by Martal24** [qd-cae/qd-cae-python#59]
Hi !
Thanks again for your great work !
i have found in my simulation results that qd.cae does not read the correct values of the strains, stress (and other time series) : the middle and inner values are swapped : using` read_states['something inner']` output the results expected for `read_states['something mid']` and the other way around. I have found this bug in all simulations I tried for this bug.

I am using LS-Dyna 11.0.0 and 11.0.1 and the last stable version of qd.cae.

Thanks for your time !

**Comment by lasso-codie** [comment]
Hey,
thanks for the info. I will look into it. In case of any trouble you can also try the D3plot reader from the [LASSO Python Library](https://github.com/lasso-gmbh/lasso-python).

**Comment by Martal24** [comment]
Hi ! Thanks for sharing this with me, I will definitively look into it !

**Comment by lasso-codie** [comment]
@Martal24 Do you really recognize this for strain as well? Since strain only has 2 layers (inner and outer). At the point where I [compute it in the code](https://github.com/qd-cae/qd-cae-python/blob/356e43d0a5364133ab5fdae2d02b9c8903e7716a/qd/cae/dyna_cpp/utility/FEM_Utility.hpp#L26), I can't find any issue there. [The switch codes are fine](https://github.com/qd-cae/qd-cae-python/blob/2d480737db7a2db280ab51ac4b0ef5db579a7981/qd/cae/dyna_cpp/dyna/d3plot/D3plot.cpp#L1562). Based on the code, inner and outer could be switched but I don't see where inner and mid could be switched.
