### ISSUE TITLE
DES force chains (Discrete element method)

### ISSUE THREAD

**Issue by cwangbh** [qd-cae/qd-cae-python#74]
Hi, 

Is is possible to extract the force chain data (force between the DES particles) by using qd?

Thanks in advance
Chao

**Comment by lasso-codie** [comment]
I have good and bad news. The good news is DES is entirely supported by the successor [lasso-python](https://github.com/lasso-gmbh/lasso-python) under the [ArrayType](https://lasso-gmbh.github.io/lasso-python/build/html/dyna/ArrayType.html) name `"airbag_particle_*"`. The bad news is that there is no force between particles output at all according to the file specs:

![grafik](https://user-images.githubusercontent.com/5020407/96630403-4357ca80-1315-11eb-9d97-6ae57d0e362f.png)
 
Please note qd is not developed anymore due to lacking support. If you want to encourage it's revival support it through [patreon](https://www.patreon.com/qd_cae).
